### ISSUE TITLE
When hovering checkbox, it hides.

### ISSUE THREAD

**Issue by yerassyl** [rollincode/rails_admin_theme#1]
When hovering any checkbox it hides itself. Also it seams that checkboxes are not clickable.
B.T.W while including this theme I commented icheck and imports in theming.scss because didn't find that files in repo.

**Comment by nicovak** [comment]
Icheck is set as depedency in `rails_admin_rollincode.gemspec` , `@import "icheck/flat/all";` is included in the `theming.scss`. Maybe a missed something ?
All JS is set in `app/assets/javascripts/rails_admin/custom/ui.js`, but you will have to create this file as said in the README.md

Also, could you try to add `gem 'icheck-rails'` in your `Gemfile` ? Have you any console error in your browser ?

**Comment by nicovak** [comment]
Mea culpa https://github.com/rollincode/rails_admin_theme/commit/e4364f1f5bf5c6763d79bf8d67cfa10e9a339875
