### ISSUE TITLE
To add better README.md

### ISSUE THREAD

**Issue by mbaev** [rollincode/rails_admin_theme#2]
Hi! This is fantastic theme for rails, but I'm new in the rails and I don't understand how to setup it.
Maybe you can to add more info abot setting up the gem? It's will very helpful!
Example of god readme for me: https://github.com/konjoot/rails_admin_flatly_theme

I perfromed try to instal your theme by manual from here https://github.com/konjoot/rails_admin_flatly_theme, but after re-run "rails s" I see error:
![rails-admin-theme](https://cloud.githubusercontent.com/assets/6450526/15440920/24ab98f2-1ee9-11e6-87bb-6aca7bc17816.png)

Maybe I doing something wrong?

Gemfile

```
gem 'rails_admin_rollincode', github: 'rollincode/rails_admin_theme'
gem 'rails_admin'
```

Application.rb

```
    ENV['RAILS_ADMIN_THEME'] = 'rollincode'
```

I have all styles in SASS ext and

```
  config.assets.css_compressor = :sass
  config.sass.preferred_syntax = :sass
```

**Comment by nicovak** [comment]
Sorry for the readme, It's still a Work In Progress, your error means you cant find froala , a wysiwyg used in the theme. I already noticed this issue, I'll correct It when I'll have some free time.

The fast way to correct It, is to add these lines to your gemfile.

```
gem 'wysiwyg-rails'
gem 'icheck-rails'
```

Can you try It ?

PS: full working example: https://github.com/rollincode/rollinbox

**Comment by nicovak** [comment]
Readme improved https://github.com/rollincode/rails_admin_theme/commit/d85ac9b563d119adfd8d9b73adaa7096d26463f4

I hope everyting will works normally now,

**Comment by mbaev** [comment]
I tried to use your solution and... it works! This is fantastic! Thanks for your job and fast response =)

**Comment by nicovak** [comment]
Great, you'r welcome. Thank you for posting issue and helping to improve the theme.
