### ISSUE TITLE
a.navbar-brand width: 100% problem

### ISSUE THREAD

**Issue by etagwerker** [rollincode/rails_admin_theme#5]
Hello, 

I found this issue when using the theme: 

![navbar-issue](https://cloud.githubusercontent.com/assets/17584/15963382/e0332302-2ee7-11e6-82d2-49ca6b6e4523.png)

It goes away if you remove `width: 100%` from `a.navbar-brand`

I'm not sure if that's the best solution. I could send a PR if you are interested. 

Thanks!

**Comment by nicovak** [comment]
Thank you for reporting that issue, which web browser are you using ? I can't reproduce the issue.

**Comment by magnocosta** [comment]
Hello,

I am detected this issue too. I am using Chrome Versão 50.0.2661.102 (64-bit)

Att,

**Comment by etagwerker** [comment]
@nicovak I was using Chrome version 50.0.2661.102 (64-bit) on Mac OS X 10.11.5

**Comment by matthv** [comment]
Finally, I have reproduced this issue. @nicovak it's a string length bug. @etagwerker thank you, but your pull request does not fix the bug completely if the "app_name" is too large. I suggest to add `white-space: nowrap;`
Someone can test with a big string ?

**Comment by etagwerker** [comment]
@matthv Weird, I just tested with a big string and it seems to work fine. What browser did you use to test my solution? 

![screen shot 2016-06-10 at 4 30 29 pm](https://cloud.githubusercontent.com/assets/17584/15976371/bfd7aa1a-2f28-11e6-9a9a-085ec3e36446.png)

**Comment by matthv** [comment]
I was using chrome version 51.0.2704.84 (64-bit) on Mac OS X 10.11.5.
It seems work fine with big word 
<img width="497" alt="capture d ecran 2016-06-11 a 02 27 41" src="https://cloud.githubusercontent.com/assets/10195400/15981899/9f9121ce-2f7c-11e6-92d6-f4b3ee34beb5.png">
But same test with multiple spaces 
<img width="320" alt="capture d ecran 2016-06-11 a 02 28 32" src="https://cloud.githubusercontent.com/assets/10195400/15981911/c3828de8-2f7c-11e6-8883-9967052a1404.png">

Finally with `white-space: nowrap;`
<img width="451" alt="capture d ecran 2016-06-11 a 02 29 03" src="https://cloud.githubusercontent.com/assets/10195400/15981920/da421de6-2f7c-11e6-9b84-6bb5357c10b1.png">

**Comment by nicovak** [comment]
Two commits have been pushed:

Clean code (multiple css declaration of `navbar-brand`)
https://github.com/rollincode/rails_admin_theme/commit/2124e988b21652b657b006c1182ca284055ec072

width 100% removed
https://github.com/rollincode/rails_admin_theme/commit/d4433adc7f725ce5605525751068ffcb6d54e368

It's on master branch but I'll create a new version on rubygem.org
