### ISSUE TITLE
Smartphones layout not responsive

### ISSUE THREAD

**Issue by luismelodev** [rollincode/rails_admin_theme#7]
Hello,

I found a problem when using at my mobile device.

It happens that the layout shows like a full desktop website, and not responsive mobile one...

**Comment by nicovak** [comment]
I think the issue comes from rails_admin Itself. We just created a theme to override default css.

https://github.com/sferik/rails_admin/blob/master/app/views/layouts/rails_admin/application.html.haml

`<meta name="viewport" content="width=device-width, initial-scale=1">` is not present.

**Comment by luismelodev** [comment]
That's correct...
I had _solved_ the problem by adding the tag on document ready state.
I will open the issue on RailsAdmin issues.

**Comment by nicovak** [comment]
You can also override rails admin layout easily.

**Comment by luismelodev** [comment]
However, other users have the same problem as I do. It would be nice if
they change the global layout.

2016-06-27 7:37 GMT-03:00 Kovacs Nicolas notifications@github.com:

> You can also override rails admin layout easily.
>
