### ISSUE TITLE
bold font not available

### ISSUE THREAD

**Issue by loicginoux** [rollincode/rails_admin_theme#8]
styling with `<strong>` or `<b>` does not do anything.
You should update your imported google font from 

```
@import url(https://fonts.googleapis.com/css?family=Raleway;
```

to 

```
@import url(https://fonts.googleapis.com/css?family=Raleway:400,700);
```

**Comment by nicovak** [comment]
Thanks ;)

https://github.com/rollincode/rails_admin_theme/commit/183867eee965562911b8b705d4cb43633181a5f4
