### ISSUE TITLE
Odd behaviour with iPad size

### ISSUE THREAD

**Issue by Joshfindit** [rollincode/rails_admin_theme#9]
When using this theme on an iPad Air, the columns break out on the right-hand side:

![2016-08-24 10 15 24](https://cloud.githubusercontent.com/assets/1937155/17932122/eede450c-69e4-11e6-8427-1bbacf9965e7.png)

Dragging to the left to reveal them does this:

![2016-08-24 10 15 28](https://cloud.githubusercontent.com/assets/1937155/17932133/fb4e0d4a-69e4-11e6-995c-7ea928b5160d.png)

Note: It still happens in landscape mode:

![2016-08-24 10 15 40](https://cloud.githubusercontent.com/assets/1937155/17932148/0dc43bde-69e5-11e6-9cf6-c8a74521749b.png)

**Comment by nicovak** [comment]
Hello, have your tried without the theme ? I think the issue comes from the original repo.

**Comment by nicovak** [comment]
Seems to be fixed with new rails_admin version ( > 1 )
